include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_double_quotes: false
    require_trailing_commas: true
    avoid_print: false
    unnecessary_await_in_return: false
    avoid_relative_lib_imports: true

analyzer:
  # ignore generated files
  exclude:
    - "lib/icons/generated_icons.dart"
    - "**/*.g.dart"
    - "**/*.gen.dart"
    - "**/*.freezed.dart"

  # for freezed
  errors:
    invalid_annotation_target: ignore

  # for riverpod
  plugins:
    - custom_lint